meta:
    name: CP10CNSM
    array: 'Coastal Pioneer MAB'
    deployment: 1
    deploy_name: D0001
    category: 'Surface Mooring'
    subcategory: 'High Power'
    disposition: deployed
    start_date: 2024-04-03T13:57:00.000Z
    stop_date: None
    latitude: 35.94988
    longitude: -75.11943
    site_depth: 32
    watch_circle: 100
    deploy_cruise: AR82
    recover_cruise: None
paths:
    raw: /home/ooiuser/data/raw
    parsed: /home/ooiuser/data/parsed
    processed: /home/ooiuser/data/processed
