#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@package cgsn_processing.process.configs.attr_fdchp
@file cgsn_processing/process/configs/attr_fdchp.py
@author Christopher Wingard
@brief Attributes for the FDCHP variables
"""

FDCHP = {
    'global': {
        'title': 'Summarized Flux Direct Covariance Sensor Measurements',
        'summary': 'Records the hourly summarized flux direct covariance measurements from the FDCHP.',
    },
    'start_time': {},
    'processing_version': {},
    'status': {},
    'avg_wind_u': {},
    'avg_wind_v': {},
    'avg_wind_w': {},
    'speed_of_sound': {},
    'std_wind_u': {},
    'std_wind_v': {},
    'std_wind_w': {},
    'std_speed_of_sound': {},
    'max_wind_u': {},
    'max_wind_v': {},
    'max_wind_w': {},
    'max_speed_of_sound': {},
    'min_wind_u': {},
    'min_wind_v': {},
    'min_wind_w': {},
    'min_speed_of_sound': {},
    'acceleration_x': {},
    'acceleration_y': {},
    'acceleration_z': {},
    'std_acc_x': {},
    'std_acc_y': {},
    'std_acc_z': {},
    'max_acc_x': {},
    'max_acc_y': {},
    'max_acc_z': {},
    'min_acc_x': {},
    'min_acc_y': {},
    'min_acc_z': {},
    'rate_x': {},
    'rate_y': {},
    'rate_z': {},
    'std_rate_x': {},
    'std_rate_y': {},
    'std_rate_z': {},
    'max_rate_x': {},
    'max_rate_y': {},
    'max_rate_z': {},
    'min_rate_x': {},
    'min_rate_y': {},
    'min_rate_z': {},
    'heading': {},
    'pitch': {},
    'roll': {},
    'std_heading': {},
    'std_pitch': {},
    'std_roll': {},
    'max_heading': {},
    'max_pitch': {},
    'max_roll': {},
    'min_heading': {},
    'min_pitch': {},
    'min_roll': {},
    'u_corrected': {},
    'v_corrected': {},
    'w_corrected': {},
    'std_u_corrected': {},
    'std_v_corrected': {},
    'std_w_corrected': {},
    'wind_speed': {},
    'momentum_flux_uw': {},
    'momentum_flux_vw': {},
    'buoyancy_flux': {},
    'wave_motion': {}
}
