#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@package cgsn_processing.process.configs.attr_RDA
@file cgsn_processing/process/configs/attr_RDA.py
@author Joe Futrelle
@brief Attributes for the RDA variables
"""

RDA = {
    'global': {
        'title': 'Downwelling Spectral Irradiance at 7 meters',
        'summary': 'Downwelling spectral irradiance measured over 7 wavelengths at 7 meter depth',
        'project': 'Ocean Observatories Initiative',
        'institution': 'Coastal and Global Scales Nodes, (CGSN)',
        'acknowledgement': 'National Science Foundation',
        'references': 'http://oceanobservatories.org',
        'creator_name': 'Christopher Wingard',
        'creator_email': 'cwingard@coas.oregonstate.edu',
        'creator_url': 'http://oceanobservatories.org',
    },
    'deploy_id': {
        'long_name': 'Deployment ID',
        'standard_name': 'deployment_id',
        'units': '1',
    },
    'date_time_string': {
        'long_name': 'Date and Time Stamp',
        'standard_name': 'date_time_string',
        'units': '1',
    },
    'depth': {
        'long_name': 'Sensor Depth',
        'standard_name': 'depth_of_sensor_below_water',
        'units': 'm',
        'positive': 'down',
        'axis': 'Z',
        'valid_min': '-10000',
        'valid_max': '1000',
    },
    'main_voltage': {'units': 'V'},
    'main_current': {'units': 'mA'},
    'error_flags': {'units': '1'},
    'rda_type': {'units': '1'},
    'ef1_no_error': {'units': '1'},
    'ef1_high_voltage_input_undervoltage': {'units': '1'},
    'ef1_high_voltage_input_overvoltage': {'units': '1'},
    'ef1_high_voltage_input_power_sensor_fault': {'units': '1'},
    'ef1_mpm_internal_over_temp': {'units': '1'},
    'ef1_mpea_hotel_power_coverter_over_temp': {'units': '1'},
    'ef1_5v_hotel_power_undervoltage': {'units': '1'},
    'ef1_5v_hotel_power_overvoltage': {'units': '1'},
    'ef1_microcontroller_core_undervoltage': {'units': '1'},
    'ef1_microcontroller_core_overvoltage': {'units': '1'},
    'ef1_hotel_power_status_sensor_fault': {'units': '1'},
    'ef1_mpea_reset_flag': {'units': '1'},
    'ef1_converter_1_input_overcurrent': {'units': '1'},
    'ef1_converter_1_output_overvoltage': {'units': '1'},
    'ef1_converter_1_output_undervoltage': {'units': '1'},
    'ef1_converter_1_output_overcurent': {'units': '1'},
    'ef1_converter_1_dc_converter_fault': {'units': '1'},
    'ef1_converter_1_input_sensor_fault': {'units': '1'},
    'ef1_converter_1_output_sensor_fault': {'units': '1'},
    'ef1_converter_2_input_overcurrent': {'units': '1'},
    'ef1_converter_2_output_overvoltage': {'units': '1'},
    'ef1_converter_2_output_undervoltage': {'units': '1'},
    'ef1_converter_2_output_overcurrent': {'units': '1'},
    'ef1_converter_2_dc_converter_fault': {'units': '1'},
    'ef1_converter_2_input_sensor_fault': {'units': '1'},
    'ef1_converter_2_output_sensor_fault': {'units': '1'},
    'ef1_converter_3_input_overcurrent': {'units': '1'},
    'ef1_converter_3_output_overvoltage': {'units': '1'},
    'ef1_converter_3_output_undervoltage': {'units': '1'},
    'ef1_converter_3_output_overcurrent': {'units': '1'},
    'ef1_converter_3_dc_converter_fault': {'units': '1'},
    'ef1_converter_3_input_sensor_fault': {'units': '1'},
    'ef1_converter_3_output_sensor_fault': {'units': '1'},
    'ef2_no_error': {'units': '1'},
    'ef2_converter_4_input_overcurrent': {'units': '1'},
    'ef1_converter_4_output_overvoltage': {'units': '1'},
    'ef1_converter_4_output_undervoltage': {'units': '1'},
    'ef2_converter_4_output_overcurrent': {'units': '1'},
    'ef2_converter_4_dc_converter_fault': {'units': '1'},
    'ef2_converter_4_input_sensor_fault': {'units': '1'},
    'ef2_converter_4_output_sensor_fault': {'units': '1'}
}
