#!/usr/bin/env python
# _*_ coding: utf_8 _*_
"""
@package cgsn_processing.process.configs.attr_superv_cpm
@file cgsn_processing/process/configs/attr_superv_cpm.py
@author Christopher Wingard
@brief Attributes for the CPM Supervisor variables
"""
SUPERV = {
    'deploy_id': {
        'long_name': 'Deployment ID',
        'standard_name': 'deployment_id',
        'units': '1',
        'coordinates': 'time z latitude longitude',
        'grid_mapping': 'crs',
        'platform': 'platform',
        'ancillary_variables': 'platform',
        'coverage_content_type': 'physicalMeasurement'
    },
    'dcl_date_time_string': {
        'long_name': 'CPM Date and Time Stamp',
        'standard_name': 'cpm_date_time_string',
        'units': '1',
        'coordinates': 'time z latitude longitude',
        'grid_mapping': 'crs',
        'platform': 'platform',
        'ancillary_variables': 'platform',
        'coverage_content_type': 'physicalMeasurement'
    },
    'main_voltage': {
        'long_name': 'Main Voltage',
        'standard_name': 'main_voltage',
        'units': 'V'
         },
    'main_current': {
        'long_name': 'Main Current',
        'standard_name': 'main_current',
        'units': 'mA'
    },
    'error_flags': {},
    'temperature1': {},
    'temperature2': {},
    'temperature3': {},
    'temperature4': {},
    'temperature5': {},
    'humidity': {},
    'pressure': {},
    'ground_fault_enable': {},
    'ground_fault_isov3': {},
    'ground_fault_main': {},
    'ground_fault_sensors': {},
    'leak_detect_enable': {},
    'leak_detect_voltage1': {},
    'leak_detect_voltage2': {},
    'port1_power_state': {},
    'port1_voltage': {},
    'port1_current': {},
    'port1_error_flag': {},
    'port2_power_state': {},
    'port2_voltage': {},
    'port2_current': {},
    'port2_error_flag': {},
    'port3_power_state': {},
    'port3_voltage': {},
    'port3_current': {},
    'port3_error_flag': {},
    'port4_power_state': {},
    'port4_voltage': {},
    'port4_current': {},
    'port4_error_flag': {},
    'port5_power_state': {},
    'port5_voltage': {},
    'port5_current': {},
    'port5_error_flag': {},
    'port6_power_state': {},
    'port6_voltage': {},
    'port6_current': {},
    'port6_error_flag': {},
    'port7_power_state': {},
    'port7_voltage': {},
    'port7_current': {},
    'port7_error_flag': {},
    'port8_power_state': {},
    'port8_voltage': {},
    'port8_current': {},
    'port8_error_flag': {},
    'heartbeat_enable': {},
    'heartbeat_delta': {},
    'heartbeat_threshold': {},
    'wake_code': {},
    'wake_time_count': {},
    'wake_power_count': {},
    'power_state': {},
    'power_board_mode': {},
    'power_voltage_select': {},
    'power_voltage_main': {},
    'power_current_main': {},
    'power_voltage_12': {},
    'power_current_12': {},
    'power_voltage_24': {},
    'power_current_24': {},
    'efd_no_errors': {},
    'efd_vmain_out_of_normal_range': {},
    'efd_imain_out_of_normal_range': {},
    'efd_iseawater_gflt_iso3v3_pos_out_of_allowable_range': {},
    'efd_iseawater_gflt_iso3v3_gnd_out_of_allowable_range': {},
    'efd_iseawater_gflt_vmain_pos_out_of_allowable_range': {},
    'efd_iseawater_gflt_vmain_gnd_out_of_allowawble_range': {},
    'efd_iseawater_gflt_inst_pos_out_of_allowable_range': {},
    'efd_iseawater_gflt_inst_gnd_out_of_allowable_range': {},
    'efd_iseawater_volt_src_4_v_out_of_allowable_range': {},
    'efd_iseawater_volt_src_4_gnd_out_of_allowable_range': {},
    'efd_leak_0_voltage_exceeded_limit': {},
    'efd_leak_1_voltage_exceeded_limit': {},
    'efd_chpic_overcurrent_fault_exists': {},
    'efd_chpic_addr_1_not_responding': {},
    'efd_chpic_addr_2_not_responding': {},
    'efd_chpic_addr_3_not_responding': {},
    'efd_chpic_addr_4_not_responding': {},
    'efd_chpic_addr_5_not_responding': {},
    'efd_chpic_addr_6_not_responding': {},
    'efd_chpic_addr_7_not_responding': {},
    'efd_chpic_addr_8_not_responding': {},
    'efd_i2c_error': {},
    'efd_uart_error': {},
    'efd_mpic_brown_out_reset': {}
}
